### ISSUE TITLE
ออกแบบหน้างต่างเริ่มเกม

### ISSUE THREAD

**Issue by NEo0o0** [Vualerie/cpe103-test-group-6#10]
เป็นtheme ดนตรี

**Comment by quartins** [comment]
ออกแบบ(มีปรับเปลี่ยนพื้นหลังเพิ่มเติมภายหลัง)
![image](https://github.com/Vualerie/cpe103-test-group-6/assets/139040387/533621c0-8d6f-4f41-9570-e8adbb9f7c61)
