### ISSUE TITLE
ออกแบบหน้าเล่นเกม

### ISSUE THREAD

**Issue by NEo0o0** [Vualerie/cpe103-test-group-6#11]

**Comment by quartins** [comment]
![image](https://github.com/Vualerie/cpe103-test-group-6/assets/139040387/1305c81f-3937-474d-bd56-938b1d206d68)

**Comment by quartins** [comment]
![image](https://github.com/Vualerie/cpe103-test-group-6/assets/139040387/841c73ac-4f39-420e-9994-c8e9bbb889f3)
