### ISSUE TITLE
การทำระบบเพิ่มและลดของเลือด

### ISSUE THREAD

**Issue by NEo0o0** [Vualerie/cpe103-test-group-6#12]
การทำระบบเพิ่มและลดของเลือด(จากการกดพลาดของผู้เล่น)

**Comment by Vualerie** [comment]
bug : replay รอบ2 แล้วเลือดไม่ลด

**Comment by Vualerie** [comment]
bug : replay รอบ2 แล้วเลือดไม่ลด (แก้แล้ว)
