### ISSUE TITLE
การทำระบบการไหลมาของจังหวะ

### ISSUE THREAD

**Issue by NEo0o0** [Vualerie/cpe103-test-group-6#13]
การออกแบบการไหลออกมาของจังหวะ และรับบในการไหลออกมาของจังหวะ

**Comment by Vualerie** [comment]
bug : ตัวโน๊ตออกมาช้าช่วงกลาง-ท้ายเพลง & feedback msg หาย

**Comment by Vualerie** [comment]
bug : โน๊ตแถวเดียวกันที่ระยะเวลาต่างกันแต่กดแล้วหายพร้อมกัน + feedback msg ขึ้นทับกัน

**Comment by Vualerie** [comment]
แก้หมดแล้ว

**Comment by Vualerie** [comment]
ตัวโน๊ตบัค ไหลไปหาตรงกลาง

**Comment by Vualerie** [comment]
ตัวโน๊ตบัค ไหลไปหาตรงกลาง (แก้แล้ว)

**Comment by Vualerie** [comment]
finished!!!
