### ISSUE TITLE
ระบบการเก็บscore

### ISSUE THREAD

**Issue by NEo0o0** [Vualerie/cpe103-test-group-6#15]
เก็บสถิติการกดผิดและถูกของผู้เล่นเพื่อนำไปคำนวนscoreตอนจบเกม

**Comment by Vualerie** [comment]
จบเกมแล้วคำนวณscoreกับaccuracyเสร็จแล้วแต่noteยังไหลลงมาเรื่อยๆ

**Comment by Vualerie** [comment]
จบเกมแล้วคำนวณscoreกับaccuracyเสร็จแล้วแต่noteยังไหลลงมาเรื่อยๆ(แก้แล้ว)

**Comment by Vualerie** [comment]
highest combo ไม่ขึ้น

**Comment by Vualerie** [comment]
highest combo ไม่ขึ้น (แก้แล้ว)

**Comment by NEo0o0** [comment]
แก้ระบบสกอร์เรียบร้อยแล้วคำนวนได้ทั้ง  score accuracy และ Highest combo
